# Generated by Django 3.0.6 on 2020-08-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20200822_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('picture', models.URLField()),
                ('nutriscore', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=250)),
                ('picture_nutrition', models.URLField(default='0000000')),
                ('favorite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Favorite')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
